# See https://damir.cavar.me/pynotebooks/Python_Tutorial_HMM.html


In [1]:
import numpy

In [2]:
stateMatrix = numpy.matrix("0.7 0.3; 0.5 0.5")

In [3]:
stateMatrix

matrix([[0.7, 0.3],
        [0.5, 0.5]])

In [4]:
emissionMatrix = numpy.matrix("0.6 0.1 0.3; 0.1 0.7 0.2")

In [5]:
emissionMatrix

matrix([[0.6, 0.1, 0.3],
        [0.1, 0.7, 0.2]])

In [6]:
initialMatrix = numpy.matrix("1 0")


In [7]:
initialMatrix

matrix([[1, 0]])