# A Simple Exploration of a Markov Chain

## From Normalized Nerd

- https://www.youtube.com/watch?v=i3AkTO9HLXo

In [4]:
import numpy as np

In [12]:
tm = np.matrix([[0.2, 0.6, 0.2], [0.3, 0, 0.7], [0.5, 0, 0.5]])
display(tm)

matrix([[0.2, 0.6, 0.2],
        [0.3, 0. , 0.7],
        [0.5, 0. , 0.5]])

In [28]:
evals, evecs = np.linalg.eig(tm.T)

In [33]:
evals

array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j])

In [30]:
evecs[0]

matrix([[-0.58746336+0.j        , -0.16984156+0.35355339j,
         -0.16984156-0.35355339j]])

In [36]:
evals[0].sum()

(1.000000000000001+0j)

In [37]:
print(evecs)


[[-0.58746336+0.j         -0.16984156+0.35355339j -0.16984156-0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467-0.35355339j -0.50952467+0.35355339j]]


In [39]:
print(evecs[1])

[[-0.35247801+0.j  0.67936622+0.j  0.67936622-0.j]]


In [41]:
evals

array([ 1.  +0.j       , -0.15+0.3122499j, -0.15-0.3122499j])

In [48]:
tmA = np.matrix([[0.5, 0.2, 0.3],[0.6, 0.2, 0.2], [0.1, 0.8, 0.1]])

In [49]:
display(tmA)


matrix([[0.5, 0.2, 0.3],
        [0.6, 0.2, 0.2],
        [0.1, 0.8, 0.1]])

In [50]:
tmA2 = np.matmul(tmA, tmA)

In [51]:
display(tmA2)

matrix([[0.4 , 0.38, 0.22],
        [0.44, 0.32, 0.24],
        [0.54, 0.26, 0.2 ]])

In [59]:
display(np.linalg.matrix_power(tmA, 8))

matrix([[0.444436  , 0.33333968, 0.22222432],
        [0.44444864, 0.33332576, 0.2222256 ],
        [0.44445504, 0.333332  , 0.22221296]])